/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkPerry' at '4/09/15 8:48 PM' with Gradle 2.6
 *
 * @author MarkPerry, @date 4/09/15 8:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
